# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'rss-02att' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for rss-02att
pod ‘SQLite.swift’, :git => ‘https://github.com/stephencelis/SQLite.swift.git’, :branch => ‘master’
pod ‘FlagKit‘, :git => ‘https://github.com/madebybowtie/FlagKit.git‘, :branch => ‘master‘
end
